In [1]:
import pandas as pd

In [2]:
data=pd.read_csv("/mnt/c/Users/LEGION/CareerSignal/ITViec_jobs.csv")
data

,job_id,slug,title,job_url,company_name,company_url,company_logo,salary,job_category,working_model,location,skills,benefits,label,posted_at,source_page,scraped_at
0,f4ed3c4e-da33-4404-aa31-fce086c3dc5b,ai-engineer-python-machine-learning-fpt-digita...,"AI Engineer (Python, Machine Learning)",https://itviec.com/it-jobs/ai-engineer-python-...,FPT Digital,https://itviec.com/companies/fpt-digital,https://itviec.com/rails/active_storage/repres...,You'll love it,AI Architect,At office,Ha Noi,"[""Python"", ""AI"", ""MongoDB"", ""LLM"", ""Deep Learn...",[],HOT,Posted\n32 minutes ago,1,2026-07-27T09:43:25.307365+00:00
1,918e3a81-c1b8-4320-983d-c950f6f4bedb,data-engineer-python-sql-power-bi-fpt-digital-...,"Data Engineer (Python, SQL, Power BI)",https://itviec.com/it-jobs/data-engineer-pytho...,FPT Digital,https://itviec.com/companies/fpt-digital,https://itviec.com/rails/active_storage/repres...,You'll love it,Data Engineer,At office,Ho Chi Minh,"[""Data modeling"", ""Data Engineer"", ""Power BI"",...",[],HOT,Posted\n36 minutes ago,1,2026-07-27T09:43:25.307365+00:00
2,238dbb5f-1d0a-444c-96df-773797d4498e,analyst-optimization-specialist-python-c-cong-...,Analyst & Optimization Specialist (Python/C++),https://itviec.com/it-jobs/analyst-optimizatio...,Công ty cổ phần hàng hải Vsico,https://itviec.com/companies/cong-ty-co-phan-h...,https://itviec.com/rails/active_storage/repres...,Thỏa thuận theo năng lực,Data Analyst,Hybrid,Ha Noi,"[""Python"", ""Data Analysis"", ""Algorithms"", ""C++""]",[],HOT,Posted\n43 minutes ago,1,2026-07-27T09:43:25.307365+00:00
3,8202812d-cac4-4f4e-866a-5d1926243ec2,chuyen-vien-an-toan-thong-tin-viettel-group-5108,Chuyên viên An toàn thông tin,https://itviec.com/it-jobs/chuyen-vien-an-toan...,Viettel Group,https://itviec.com/companies/viettel-group,https://itviec.com/rails/active_storage/repres...,You'll love it,Security Engineer,At office,Ha Noi,"[""Security"", ""Software Architecture""]","[""Dẫn đầu thị trường"", ""Cơ hội thử thách và ph...",SUPER HOT,Posted\n43 minutes ago,1,2026-07-27T09:43:25.307365+00:00
4,9368228d-d23a-4361-902f-fa97f2f900db,application-support-engineer-java-oracle-sql-v...,"Application Support Engineer (Java, Oracle, SQL)",https://itviec.com/it-jobs/application-support...,Vietnamobile,https://itviec.com/companies/vietnamobile,https://itviec.com/rails/active_storage/repres...,You'll love it,IT Support,At office,Ha Noi,"[""Java"", ""SQL"", ""API"", ""Linux"", ""IT Support"", ...",[],HOT,Posted\n58 minutes ago,1,2026-07-27T09:43:25.307365+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
882,122be624-74e8-4faf-9291-b99c3ad20841,senior-ui-ux-designer-hitachi-digital-services...,Senior UI/UX Designer,https://itviec.com/it-jobs/senior-ui-ux-design...,Hitachi Digital Services,https://itviec.com/companies/hitachi-digital-s...,https://itviec.com/rails/active_storage/repres...,You'll love it,UX/UI Designer,At office,Ho Chi Minh,"[""Figma"", ""HTML"", ""Sketch"", ""Adobe XD"", ""React...",[],NaN,Posted\n35 days ago,45,2026-07-27T09:43:25.307365+00:00
883,22c08f78-8620-4e56-8abb-9778d1c641ba,senior-backend-engineer-parcel-perform-1102,Senior Backend Engineer,https://itviec.com/it-jobs/senior-backend-engi...,Parcel Perform,https://itviec.com/companies/parcel-perform,https://itviec.com/rails/active_storage/repres...,You'll love it,Backend Developer,Hybrid,Ho Chi Minh,"[""Python"", ""Kafka"", ""Django""]",[],NaN,Posted\n35 days ago,45,2026-07-27T09:43:25.307365+00:00
884,52d59b0c-8a4e-4ca1-96a7-0289fa87b79d,principal-php-software-engineer-saas-product-r...,Principal PHP Software Engineer (SaaS product),https://itviec.com/it-jobs/principal-php-softw...,Rakus Vietnam Company,https://itviec.com/companies/rakus-vietnam-com...,https://itviec.com/rails/active_storage/repres...,"1,600 - 1,800 USD",Fullstack Developer,At office,Ho Chi Minh,"[""PHP"", ""Technical Writing"", ""PostgreSql"", ""So...",[],NaN,Posted\n35 days ago,45,2026-07-27T09:43:25.307365+00:00
885,e81252ca-96d0-44b1-9d63-093ac4eea572,business-analyst-tps-software-0157,Business Analyst,https://itviec.com/it-jobs/business-analyst-tp...,TPS Software,https://itviec.com/companies/tps-software,https://itviec.com/rails/active_storage/repres...,You'll love it,Business Analyst,At office,Ho Chi Minh,"[""Business Analysis"", ""Scrum"", ""Agile"", ""Produ...",[],NaN,Posted\n35 days ago,45,2026-07-27T09:43:25.307365+00:00
886,356ba0ee-be19-4d18-881b-8eb4e9d316bd,principal-engineer-devops-timo-4044,Principal Engineer DevOps,https://itviec.com/it-jobs/principal-engineer-...,Timo,https://itviec.com/companies/timo,https://itviec.com/rails/active_storage/repres...,You'll love it,DevOps Engineer,At office,Ho Chi Minh,"[""DevOps"", ""Helm"", ""AWS"", ""CI/CD"", ""Docker"", ""...",[],NaN,Posted\n35 days ago,45,2026-07-27T09:43:25.307365+00:00

In [3]:
data.columns

Index(['job_id', 'slug', 'title', 'job_url', 'company_name', 'company_url',
       'company_logo', 'salary', 'job_category', 'working_model', 'location',
       'skills', 'benefits', 'label', 'posted_at', 'source_page',
       'scraped_at'],
      dtype='str')

In [4]:
data['company_name']

0                         FPT Digital
1                         FPT Digital
2      Công ty cổ phần hàng hải Vsico
3                       Viettel Group
4                        Vietnamobile
                    ...
882          Hitachi Digital Services
883                    Parcel Perform
884             Rakus Vietnam Company
885                      TPS Software
886                              Timo
Name: company_name, Length: 887, dtype: str

In [5]:
data[data['job_category']=='Data Engineer'].count()

job_id           31
slug             31
title            31
job_url          31
company_name     31
company_url      31
company_logo     31
salary           31
job_category     31
working_model    31
location         31
skills           31
benefits         31
label            12
posted_at        31
source_page      31
scraped_at       31
dtype: int64

In [6]:
data2=pd.read_csv("/mnt/c/Users/LEGION/CareerSignal/ingestion/topcv_it_jobs.csv")

FileNotFoundError: [Errno 2] No such file or directory: '/mnt/c/Users/LEGION/CareerSignal/ingestion/topcv_it_jobs.csv'

In [ ]:
data2

,job_id,source_page,position,tracking_id,box_type,title,company_name,salary,city,experience,...,remaining_tags,is_hot,is_urgent,is_pro_company,is_verified,verification_level,is_highlight,is_flash_job,is_diamond_employer,scraped_at
0,2247073,1,1,wqDiWOa2JDMU3lNbyNmOqGREB44dR0ktgdXa0N5D_17850...,BoxSearchResult,Kỹ Thuật Viên Camera (Camera Technician),CÔNG TY CỔ PHẦN CÔNG NGHỆ HANET,Từ 10 triệu,Hà Nội & Quảng Ninh,3 năm,...,"Network Engineer, Trung cấp trở lên",False,False,False,False,NaN,True,False,False,2026-07-26T17:40:23
1,1778187,1,2,wqDiWOa2JDMU3lNbyNmOqGREB44dR0ktgdXa0N5D_17850...,BoxSearchResult,Cloud Solution Engineer (CMC Cloud),Công ty cổ phần Hạ tầng Viễn thông CMC Telecom,Thoả thuận,Hồ Chí Minh (mới),4 năm,...,"Solution Architect, Điện toán đám mây (Cloud),...",False,False,True,True,level-five,True,False,False,2026-07-26T17:40:23
2,2228640,1,3,wqDiWOa2JDMU3lNbyNmOqGREB44dR0ktgdXa0N5D_17850...,BoxSearchResult,Nhân Viên Thiết Kế & Lập Trình CNC - [Thu Nhập...,CÔNG TY CỔ PHẦN IBS,10 - 15 triệu,Tây Ninh (mới),2 năm,...,"Chuyên môn Thiết kế/chế tạo máy khác, Cơ khí /...",False,False,False,True,level-five,True,False,False,2026-07-26T17:40:23
3,2220160,1,4,wqDiWOa2JDMU3lNbyNmOqGREB44dR0ktgdXa0N5D_17850...,BoxSearchResult,Solution Architect (AI Domain),CÔNG TY CỔ PHẦN CMC OPENAI,Tới 65 triệu,Hà Nội,5 năm,...,"5 năm kinh nghiệm chuyên môn, Solution Archite...",False,False,False,True,level-five,True,False,False,2026-07-26T17:40:23
4,2250125,1,5,wqDiWOa2JDMU3lNbyNmOqGREB44dR0ktgdXa0N5D_17850...,BoxSearchResult,Kỹ Sư Lập Trình C++,Công ty TNHH Công Nghệ Dicom,Thoả thuận,Hà Nội,Dưới 1 năm,...,"Mobile Developer, IT - Phần mềm, Viễn thông, T...",False,False,False,True,level-five,True,False,False,2026-07-26T17:40:23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2093,1556013,64,46,wqDiWOa2JDMU3lNbyNmOqGREB44dR0ktgdXa0N5D_17850...,BoxSearchResult,Trưởng Phòng Kinh Doanh Phần Mềm Và Giải Pháp,CÔNG TY CỔ PHẦN GIẢI PHÁP CÔNG NGHỆ BZISOFT,Tới 30 triệu,Hồ Chí Minh (mới) & Hà Nội,3 năm,...,"3 năm kinh nghiệm chuyên môn, Kinh doanh phần ...",False,False,False,False,NaN,False,False,False,2026-07-26T17:40:23
2094,2181160,64,47,wqDiWOa2JDMU3lNbyNmOqGREB44dR0ktgdXa0N5D_17850...,BoxSearchResult,Sale Intern,FPT IS,Tới 0.0 triệu,Hà Nội,Không yêu cầu,...,"Bán hàng kỹ thuật IT, B2B, IT - Phần mềm, Tuổi...",False,False,True,True,level-five,False,False,False,2026-07-26T17:40:23
2095,2216337,64,48,wqDiWOa2JDMU3lNbyNmOqGREB44dR0ktgdXa0N5D_17850...,BoxSearchResult,Product Manager,Công ty TNHH BTASKEE,Thoả thuận,Hồ Chí Minh (mới),3 năm,...,"3 năm kinh nghiệm chuyên môn, Product Owner/Pr...",False,False,False,False,NaN,False,False,False,2026-07-26T17:40:23
2096,2214458,64,49,wqDiWOa2JDMU3lNbyNmOqGREB44dR0ktgdXa0N5D_17850...,BoxSearchResult,BrSE – AI & Solution (Lead),"TECHVIFY SOFTWARE., JSC",Thoả thuận,Hà Nội & 2 nơi khác,2 năm,...,Đại Học trở lên,False,False,False,False,NaN,False,False,False,2026-07-26T17:40:23
2097,2035701,64,50,wqDiWOa2JDMU3lNbyNmOqGREB44dR0ktgdXa0N5D_17850...,BoxSearchResult,Business Analyst (Middle) - Thu Nhập Up To 30 ...,Công ty cổ phần Công nghệ Sapo,Tới 30 triệu,Hà Nội,3 năm,...,"Business Analyst (Phân tích nghiệp vụ), IT - P...",False,False,False,True,level-five,False,False,True,2026-07-26T17:40:23

In [ ]:
data2.columns
data.columns

Index(['job_id', 'slug', 'title', 'job_url', 'company_name', 'company_url',
       'company_logo', 'salary', 'job_category', 'working_model', 'location',
       'skills', 'benefits', 'label', 'posted_at', 'source_page',
       'scraped_at'],
      dtype='str')

In [ ]:
data[data['label'].notnull()]

,job_id,slug,title,job_url,company_name,company_url,company_logo,salary,job_category,working_model,location,skills,benefits,label,posted_at,source_page,scraped_at
0,f4ed3c4e-da33-4404-aa31-fce086c3dc5b,ai-engineer-python-machine-learning-fpt-digita...,"AI Engineer (Python, Machine Learning)",https://itviec.com/it-jobs/ai-engineer-python-...,FPT Digital,https://itviec.com/companies/fpt-digital,https://itviec.com/rails/active_storage/repres...,You'll love it,AI Architect,At office,Ha Noi,"[""Python"", ""AI"", ""MongoDB"", ""LLM"", ""Deep Learn...",[],HOT,Posted\n32 minutes ago,1,2026-07-27T09:43:25.307365+00:00
1,918e3a81-c1b8-4320-983d-c950f6f4bedb,data-engineer-python-sql-power-bi-fpt-digital-...,"Data Engineer (Python, SQL, Power BI)",https://itviec.com/it-jobs/data-engineer-pytho...,FPT Digital,https://itviec.com/companies/fpt-digital,https://itviec.com/rails/active_storage/repres...,You'll love it,Data Engineer,At office,Ho Chi Minh,"[""Data modeling"", ""Data Engineer"", ""Power BI"",...",[],HOT,Posted\n36 minutes ago,1,2026-07-27T09:43:25.307365+00:00
2,238dbb5f-1d0a-444c-96df-773797d4498e,analyst-optimization-specialist-python-c-cong-...,Analyst & Optimization Specialist (Python/C++),https://itviec.com/it-jobs/analyst-optimizatio...,Công ty cổ phần hàng hải Vsico,https://itviec.com/companies/cong-ty-co-phan-h...,https://itviec.com/rails/active_storage/repres...,Thỏa thuận theo năng lực,Data Analyst,Hybrid,Ha Noi,"[""Python"", ""Data Analysis"", ""Algorithms"", ""C++""]",[],HOT,Posted\n43 minutes ago,1,2026-07-27T09:43:25.307365+00:00
3,8202812d-cac4-4f4e-866a-5d1926243ec2,chuyen-vien-an-toan-thong-tin-viettel-group-5108,Chuyên viên An toàn thông tin,https://itviec.com/it-jobs/chuyen-vien-an-toan...,Viettel Group,https://itviec.com/companies/viettel-group,https://itviec.com/rails/active_storage/repres...,You'll love it,Security Engineer,At office,Ha Noi,"[""Security"", ""Software Architecture""]","[""Dẫn đầu thị trường"", ""Cơ hội thử thách và ph...",SUPER HOT,Posted\n43 minutes ago,1,2026-07-27T09:43:25.307365+00:00
4,9368228d-d23a-4361-902f-fa97f2f900db,application-support-engineer-java-oracle-sql-v...,"Application Support Engineer (Java, Oracle, SQL)",https://itviec.com/it-jobs/application-support...,Vietnamobile,https://itviec.com/companies/vietnamobile,https://itviec.com/rails/active_storage/repres...,You'll love it,IT Support,At office,Ha Noi,"[""Java"", ""SQL"", ""API"", ""Linux"", ""IT Support"", ...",[],HOT,Posted\n58 minutes ago,1,2026-07-27T09:43:25.307365+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319,b7e9d997-6b7b-42a2-985a-0108d9dace48,it-manager-azure-cloud-networking-cong-ty-tnhh...,"IT Manager (Azure, Cloud & Networking)",https://itviec.com/it-jobs/it-manager-azure-cl...,CÔNG TY TNHH OTSUKA NUTRACEUTICAL VIỆT NAM (ONV),https://itviec.com/companies/cong-ty-tnhh-otsu...,https://itviec.com/rails/active_storage/repres...,You'll love it,Manager,At office,Ho Chi Minh,"[""Cloud"", ""Cybersecurity"", ""Project Management...",[],NEW,Posted\n2 days ago,16,2026-07-27T09:43:25.307365+00:00
320,fb758faa-8a3e-4ed4-8edc-1ff3f98a069e,senior-mid-level-web-developer-python-typescri...,"Senior/ Mid-level Web Developer (Python, TypeS...",https://itviec.com/it-jobs/senior-mid-level-we...,CÔNG TY TNHH WECAT,https://itviec.com/companies/cong-ty-tnhh-wecat,https://itviec.com/rails/active_storage/repres...,You'll love it,Fullstack Developer,At office,Da Nang,"[""Fullstack"", ""Flask"", ""Django"", ""Database"", ""...",[],NEW,Posted\n2 days ago,17,2026-07-27T09:43:25.307365+00:00
321,1803e3e5-7aeb-4bc7-a14e-d6cbcb3da529,ai-automation-software-engineer-n4-japanese-co...,AI Automation Software Engineer (N4 Japanese),https://itviec.com/it-jobs/ai-automation-softw...,CÔNG TY TNHH OHARA PLASTICS,https://itviec.com/companies/cong-ty-tnhh-ohar...,https://itviec.com/rails/active_storage/repres...,You'll love it,AI / Machine Learning Engineer,At office,Ha Noi,"[""AI"", ""Japanese IT Communication"", ""Japanese""...",[],NEW,Posted\n2 days ago,17,2026-07-27T09:43:25.307365+00:00
322,3fd60960-b2f0-4e20-92ea-0380fc2b15f1,analytics-engineer-airr-labs-3510,Analytics Engineer,https://itviec.com/it-jobs/analytics-engineer-...,AIRR Labs,https://itviec.com/companies/airr-labs,https://itviec.com/rails/active_storage/repres...,"1,000 - 2,000 USD",Analytics Engineer,At office,Ho Chi Minh,"[""SQL"", ""Statistical Analysis"", ""Data Warehous...",[],NEW,Posted\n2 days ago,17,2026-07-27T09:43:25.307365+00:00
705,995c8e30-2919-44e8-bfd6-5f7a1355c2a9,remote-cyber-security-lead-owasp-aws-cissp-org...,"Remote - Cyber Security Lead (OWASP, AWS, CISSP)",https://itviec.com/it-jobs/remote-cyber-securi...,OrgScale Recruitment,https://itviec.com/companies/orgscale-recruitment,https://itviec.com/rails/active_storage/repres...,"2,000 - 5,000 USD",Solution Architect,Remote,Ho Chi Minh - Ha Noi - Da Nang,"[""Cybersecurity"", ""Predictive Analytics"", ""Clo...",[],HEADHUNT,Posted\n25 days ago,36,2026-07-27T09:43:25.307365+00:00

In [ ]:
data[data['benefits'] !='[]']['benefits']

3      ["Dẫn đầu thị trường", "Cơ hội thử thách và ph...
6      ["Very competitive remuneration package", "Bui...
7      ["Very competitive remuneration package", "Bui...
8      ["Môi trường làm việc đa quốc gia", "Cơ hội th...
9      ["Top-ranking of corporate value increase rate...
                             ...
755    ["Year-end Bonus & Performance review twice a ...
761    ["Very competitive remuneration package", "Bui...
781    ["Stock options", "Vietnam labor law contract ...
783    ["Salary up to $2500", "13th month of salary",...
786    ["Very attractive salary package and Bonus", "...
Name: benefits, Length: 223, dtype: str

In [ ]:
data2['job_id'].sort_values(ascending=False)

516     2250531
520     2250486
83      2250430
9       2250378
522     2250372
         ...
1681     639349
1979     575992
1084     546494
1890     500122
1887     293807
Name: job_id, Length: 2098, dtype: int64

In [ ]:
data[data.duplicated()]

Empty DataFrame
Columns: [job_id, slug, title, job_url, company_name, company_url, company_logo, salary, job_category, working_model, location, skills, benefits, label, posted_at, source_page, scraped_at]
Index: []

In [ ]:
data2[['posted_time','updated_time','scraped_at']]

             posted_time            updated_time           scraped_at
0      Đăng 3 ngày trước     Cập nhật 1 giây tới  2026-07-26T17:40:23
1      Đăng 3 ngày trước   Cập nhật 3 giây trước  2026-07-26T17:40:23
2      Đăng 3 ngày trước   Cập nhật 1 phút trước  2026-07-26T17:40:23
3      Đăng 1 tuần trước   Cập nhật 1 phút trước  2026-07-26T17:40:23
4      Đăng 1 ngày trước   Cập nhật 4 phút trước  2026-07-26T17:40:23
...                  ...                     ...                  ...
2093  Đăng 1 tháng trước  Cập nhật 1 tháng trước  2026-07-26T17:40:23
2094  Đăng 1 tháng trước  Cập nhật 1 tháng trước  2026-07-26T17:40:23
2095  Đăng 1 tháng trước  Cập nhật 1 tháng trước  2026-07-26T17:40:23
2096  Đăng 1 tháng trước  Cập nhật 1 tháng trước  2026-07-26T17:40:23
2097  Đăng 1 tháng trước  Cập nhật 1 tháng trước  2026-07-26T17:40:23

[2098 rows x 3 columns]

In [ ]:
dataITViec=pd.read_csv("/mnt/c/Users/LEGION/CareerSignal/ITViec_jobs.csv")
datatopcv=pd.read_csv("/mnt/c/Users/LEGION/CareerSignal/topcv_it_jobs.csv")

In [ ]:
dataITViec

,job_id,slug,title,job_url,company_name,company_url,company_logo,salary,job_category,working_model,location,skills,benefits,label,posted_at,source_page,scraped_at
0,f4ed3c4e-da33-4404-aa31-fce086c3dc5b,ai-engineer-python-machine-learning-fpt-digita...,"AI Engineer (Python, Machine Learning)",https://itviec.com/it-jobs/ai-engineer-python-...,FPT Digital,https://itviec.com/companies/fpt-digital,https://itviec.com/rails/active_storage/repres...,You'll love it,AI Architect,At office,Ha Noi,"[""Python"", ""AI"", ""MongoDB"", ""LLM"", ""Deep Learn...",[],HOT,Posted\n32 minutes ago,1,2026-07-27T09:43:25.307365+00:00
1,918e3a81-c1b8-4320-983d-c950f6f4bedb,data-engineer-python-sql-power-bi-fpt-digital-...,"Data Engineer (Python, SQL, Power BI)",https://itviec.com/it-jobs/data-engineer-pytho...,FPT Digital,https://itviec.com/companies/fpt-digital,https://itviec.com/rails/active_storage/repres...,You'll love it,Data Engineer,At office,Ho Chi Minh,"[""Data modeling"", ""Data Engineer"", ""Power BI"",...",[],HOT,Posted\n36 minutes ago,1,2026-07-27T09:43:25.307365+00:00
2,238dbb5f-1d0a-444c-96df-773797d4498e,analyst-optimization-specialist-python-c-cong-...,Analyst & Optimization Specialist (Python/C++),https://itviec.com/it-jobs/analyst-optimizatio...,Công ty cổ phần hàng hải Vsico,https://itviec.com/companies/cong-ty-co-phan-h...,https://itviec.com/rails/active_storage/repres...,Thỏa thuận theo năng lực,Data Analyst,Hybrid,Ha Noi,"[""Python"", ""Data Analysis"", ""Algorithms"", ""C++""]",[],HOT,Posted\n43 minutes ago,1,2026-07-27T09:43:25.307365+00:00
3,8202812d-cac4-4f4e-866a-5d1926243ec2,chuyen-vien-an-toan-thong-tin-viettel-group-5108,Chuyên viên An toàn thông tin,https://itviec.com/it-jobs/chuyen-vien-an-toan...,Viettel Group,https://itviec.com/companies/viettel-group,https://itviec.com/rails/active_storage/repres...,You'll love it,Security Engineer,At office,Ha Noi,"[""Security"", ""Software Architecture""]","[""Dẫn đầu thị trường"", ""Cơ hội thử thách và ph...",SUPER HOT,Posted\n43 minutes ago,1,2026-07-27T09:43:25.307365+00:00
4,9368228d-d23a-4361-902f-fa97f2f900db,application-support-engineer-java-oracle-sql-v...,"Application Support Engineer (Java, Oracle, SQL)",https://itviec.com/it-jobs/application-support...,Vietnamobile,https://itviec.com/companies/vietnamobile,https://itviec.com/rails/active_storage/repres...,You'll love it,IT Support,At office,Ha Noi,"[""Java"", ""SQL"", ""API"", ""Linux"", ""IT Support"", ...",[],HOT,Posted\n58 minutes ago,1,2026-07-27T09:43:25.307365+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
882,122be624-74e8-4faf-9291-b99c3ad20841,senior-ui-ux-designer-hitachi-digital-services...,Senior UI/UX Designer,https://itviec.com/it-jobs/senior-ui-ux-design...,Hitachi Digital Services,https://itviec.com/companies/hitachi-digital-s...,https://itviec.com/rails/active_storage/repres...,You'll love it,UX/UI Designer,At office,Ho Chi Minh,"[""Figma"", ""HTML"", ""Sketch"", ""Adobe XD"", ""React...",[],NaN,Posted\n35 days ago,45,2026-07-27T09:43:25.307365+00:00
883,22c08f78-8620-4e56-8abb-9778d1c641ba,senior-backend-engineer-parcel-perform-1102,Senior Backend Engineer,https://itviec.com/it-jobs/senior-backend-engi...,Parcel Perform,https://itviec.com/companies/parcel-perform,https://itviec.com/rails/active_storage/repres...,You'll love it,Backend Developer,Hybrid,Ho Chi Minh,"[""Python"", ""Kafka"", ""Django""]",[],NaN,Posted\n35 days ago,45,2026-07-27T09:43:25.307365+00:00
884,52d59b0c-8a4e-4ca1-96a7-0289fa87b79d,principal-php-software-engineer-saas-product-r...,Principal PHP Software Engineer (SaaS product),https://itviec.com/it-jobs/principal-php-softw...,Rakus Vietnam Company,https://itviec.com/companies/rakus-vietnam-com...,https://itviec.com/rails/active_storage/repres...,"1,600 - 1,800 USD",Fullstack Developer,At office,Ho Chi Minh,"[""PHP"", ""Technical Writing"", ""PostgreSql"", ""So...",[],NaN,Posted\n35 days ago,45,2026-07-27T09:43:25.307365+00:00
885,e81252ca-96d0-44b1-9d63-093ac4eea572,business-analyst-tps-software-0157,Business Analyst,https://itviec.com/it-jobs/business-analyst-tp...,TPS Software,https://itviec.com/companies/tps-software,https://itviec.com/rails/active_storage/repres...,You'll love it,Business Analyst,At office,Ho Chi Minh,"[""Business Analysis"", ""Scrum"", ""Agile"", ""Produ...",[],NaN,Posted\n35 days ago,45,2026-07-27T09:43:25.307365+00:00
886,356ba0ee-be19-4d18-881b-8eb4e9d316bd,principal-engineer-devops-timo-4044,Principal Engineer DevOps,https://itviec.com/it-jobs/principal-engineer-...,Timo,https://itviec.com/companies/timo,https://itviec.com/rails/active_storage/repres...,You'll love it,DevOps Engineer,At office,Ho Chi Minh,"[""DevOps"", ""Helm"", ""AWS"", ""CI/CD"", ""Docker"", ""...",[],NaN,Posted\n35 days ago,45,2026-07-27T09:43:25.307365+00:00